nodeLinker: node-modules
enableScripts: true
afterInstall: "yarn postinstall"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "@yarnpkg/plugin-after-install"
yarnPath: .yarn/releases/yarn-3.6.4.cjs
