import DESIGN_SYSTEM_ROUTES from "./routes";

export type AppParamsList = {
  [DESIGN_SYSTEM_ROUTES.MAIN]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.COLOR.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.TYPOGRAPHY.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LAYOUT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.ICONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.PICTOGRAMS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.FOUNDATION.LOGOS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BUTTONS.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.BADGE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.SELECTION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ADVICE.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ACCORDION.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.ALERT.route]: undefined;
  [DESIGN_SYSTEM_ROUTES.COMPONENTS.LIST_ITEMS.route]: undefined;
};
