name: Checks
on:
  - pull_request
jobs:
  checks:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-pr-staticcheck-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - id: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - id: setup
        name: Setup
        uses: ./.github/actions/setup
      - id: tsc
        name: Typescript
        run: yarn typecheck
      - id: prettier
        name: Prettier
        run: yarn prettier:check
      - id: lint
        name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: Build the library
        run: yarn prepack